### ISSUE TITLE
Error: Alfred preferences not found at location 

### ISSUE THREAD

**Issue by innovation-counsel** [wesbaker/alfred-goodreads-workflow#56]
This error appears similar to this issue: https://github.com/sindresorhus/alfy/issues/81

Alfred 4 with Powerpack installed.  

I have not yet set up Dropbox sync of preferences, so the Preferences file should be at its default location.

Tried:
npm install --global alfred-goodreads-workflow

Got:

> alfred-goodreads-workflow@2.1.1 postinstall /usr/local/lib/node_modules/alfred-goodreads-workflow
> alfy-init

Error: Command failed: alfred-link
Error: Alfred preferences not found at location /User...

...
at /usr/local/lib/node_modules/alfred-goodreads-workflow/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/jamesford/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at /usr/local/lib/node_modules/alfred-goodreads-workflow/node_modules/resolve-alfred-prefs/index.js:15:10\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-goodreads-workflow@2.1.1 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-goodreads-workflow@2.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wesbaker** [comment]
So I didn't get this issue when I tried reinstalling it myself. It's definitely part of `alfy`, a dependency, but I'm not sure why you're getting it. If you go to the directory it's talking about (`/Users/jamesford/Library/Preferences/`), do you see the file it's looking for?

**Comment by natterstefan** [comment]
Hi guys,

https://github.com/sindresorhus/alfy/issues/110#issuecomment-499289678 resolved the issue for me.

**Comment by wesbaker** [comment]
Thanks for following up. I've had numerous bumps by `dependabot`, but haven't released anything in a while. Let me see if that clears things up.

**Comment by natterstefan** [comment]
Hi @wesbaker,

no worries. :)

**Comment by wesbaker** [comment]
Alright, I just pushed up 2.2.0. See if that fixes things.

**Comment by natterstefan** [comment]
Can you maybe test it again @innovation-counsel? Because I applied the symlink etc. (as suggested here https://github.com/sindresorhus/alfy/issues/110#issuecomment-499289678) already.

Thanks for your time @wesbaker.
